### ISSUE TITLE
When I try to install a theme I am getting the Install package failed This can happen if the server does not have write access to the '~/Modules' or '~/Themes'  error.

### ISSUE THREAD

**Issue by TimTracy** [OrchardCMS/Orchard.Gallery#38]
have checked previous issues I believe my feed id is correct but continue to receive the above error.
 The theme gallery worked about a month ago with this same setting.

my settings gallery feed is
https://gallery.orchardproject.net/api/FeedService

**Comment by TimTracy** [comment]
I have checked previous issues I believe my feed id is correct but continue to receive the above error.
The theme gallery worked about a month ago with this same setting.

my settings gallery feed is 
https://gallery.orchardproject.net/api/FeedService

**Comment by edwardm** [comment]
I'm also experiencing this issue. I was thinking it might be my local project. But I tried on other Orchard installs, locally and in a live production server... same issue. Never saw this before until now.

**Comment by edwardm** [comment]
Anyone have any ideas on this?

**Comment by TimTracy** [comment]
I have started downloaded modules and themes and installing them locally. The orchard feed use to work fine for me and stopped working like 3 months ago on multiple computers. There seems to be no response about this issue just that the feed works. The feed worked fine 6 months ago when I first starting using orchard.

**Comment by edwardm** [comment]
@TimTracy Thanks for the reply, I will try downloading and installing manually then, thanks

**Comment by TimTracy** [comment]
If I come across any info on how to fix this issue I will forward it to you, if you could do the same.
Thanks.

**Comment by jayharris** [comment]
This appears to be an issue with the feed, not with the Orchard installation. Though the feed is at `gallery.orchardproject.com`, the Gallery's feed service is reporting the download link for each package as `orchardgallery.azurewebsites.net`. Anything request to `orchardgallery.azurewebsites.net` is returning an HTTP403.

The package won't download because of the 403, causing the installation failure.

The FeedService is using `orchardgallery.azurewebsites.net` based on [workContext.CurrentSite.BaseUrl](https://github.com/OrchardCMS/Orchard.Gallery/blob/master/Services/PackagePartFormatter.cs#L54), so I am guessing that the Gallery Settings are set to `orchardgallery.azurewebsites.net` instead of `gallery.orchardproject.net`.

**Comment by jayharris** [comment]
I think this BaseURL issue may also be the source of #37.

**Comment by sebastienros** [comment]
Fixed
